//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusalaDrones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusalaDrones.JsonResults", typeof(JsonResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE ERROR {0}.
        /// </summary>
        public static string JSON_DBERROR {
            get {
                return ResourceManager.GetString("JSON_DBERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG DRONE SERIAL NUMBER LENGHT.
        /// </summary>
        public static string JSON_DRONESNBADPROPERTY {
            get {
                return ResourceManager.GetString("JSON_DRONESNBADPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOW DRONE BATTERY.
        /// </summary>
        public static string JSON_LOWBATTERY {
            get {
                return ResourceManager.GetString("JSON_LOWBATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO MEDICATION TO LOAD.
        /// </summary>
        public static string JSON_NOMEDICATIONS {
            get {
                return ResourceManager.GetString("JSON_NOMEDICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRONE NOT AVAILABLE.
        /// </summary>
        public static string JSON_NOTAVAILABLE {
            get {
                return ResourceManager.GetString("JSON_NOTAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT FOUND.
        /// </summary>
        public static string JSON_NOTFOUND {
            get {
                return ResourceManager.GetString("JSON_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string JSON_OK {
            get {
                return ResourceManager.GetString("JSON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG DRONE DATA.
        /// </summary>
        public static string JSON_WRONGDRONEINFO {
            get {
                return ResourceManager.GetString("JSON_WRONGDRONEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG LOADING INFO DATA.
        /// </summary>
        public static string JSON_WRONGLOADINGINFO {
            get {
                return ResourceManager.GetString("JSON_WRONGLOADINGINFO", resourceCulture);
            }
        }
    }
}
